### PR TITLE
Upgrade to Wavefront opentracing SDK 2.1.2

### PR DESCRIPTION
**Pull request by haosong**
Fix https://github.com/wavefrontHQ/wavefront-spring-boot/issues/85

### CODE REVIEW

**Review by sushantdewan123 — APPROVED** [review]
lgtm!

**Comment by sushantdewan123** [comment]
PR for this github issue: https://github.com/wavefrontHQ/wavefront-spring-boot/pull/86

**Comment by snicoll** [comment]
I think that rather than duplicating the issue that was fixed in the SDK, those issues should be about general dependency upgrades. The issue isn't in this project so the current description is a bit misleading IMO.

**Review by snicoll — APPROVED** [review]

**Comment by snicoll** [comment]
Superseded by #90

**Pull request closed without merging**
