### PR TITLE
Always create WavefrontTracer in OpenTracing

### PR DESCRIPTION
**Pull request by ttddyy**
Previously, when `WavefrontSender` bean does not exist, creation of
`WavefrontTracer` is skipped. This causes a problem where we want to
use `WavefrontTracer` but not send data to Wavefront via
`WavefrontSpanReporter`.

This commit changes to always create `WavefrontTracer` but
conditionally create `WavefrontSpanReporter` when `WavefrontSender`
bean exists; otherwise, no-op reporter will be used.

To completely skip the creation of tracer, there is already
`wavefront.tracing.enabled` property available.

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Hey @ttddyy! 

What problem are we trying to solve here? Cause it seems that currently we're creating the tracing infrastructure only when the Wavefront autoconfiguration is there (it creates the Sender). It's always there cause the starter brings in actuator. So you'd have to explicitly exclude actuator to make things not work or not include the starter.

> This causes a problem where we want to use WavefrontTracer but not send data to Wavefront via WavefrontSpanReporter.

Why do you want to do this? If we're trying to achieve a situation in which you can have tracing without metrics then I don't think this is the way to solve this. The question is why should we support that in a Wavefront starter that is supposed to work with wavefront.

**Comment by ttddyy** [comment]
Hi @marcingrzejszczak 

In on-prem environment, we need to propagate Wavefront spans for logging. We use WF tracer with other reporters but not `WavefrontSpanReporter`. Also, on-prem env sets `management.metrics.export.wavefront.enabled=false` to disable sending metrics to WF.

Currently, creation of `WavefrontTracer` is skipped if `WavefrontSender` bean is not available.
Instead, we need to create a `WavefrontTracer` bean but skip `WavefrontSpanReporter` bean. So that, tracer could be used with other reporters.

For Sleuth side, since `WavefrontTracingSleuthConfiguration` only add `WavefrontSleuthSpanHandler`, the presence of `WavefrontSender` doesn't affect the creation of tracer, which is created somewhere else.
On the other hand, for OpenTracing side, `WavefrontSender` condition affects creation of `WavefrontTracer` itself.

I think this is inconsistent.
Currently, bringing tracer infrastructure has  mainly two conditions for OpenTracing side - `wavefront.tracing.enabled` property and `WavefrontSender` bean.
`wavefront.tracing.enabled` property is the ultimate one to control, but `WavefrontSender` should not control the creation of tracer.

**Comment by snicoll** [comment]
> In on-prem environment, we need to propagate Wavefront spans for logging. We use WF tracer with other reporters but not WavefrontSpanReporter. Also, on-prem env sets management.metrics.export.wavefront.enabled=false to disable sending metrics to WF.

I think the point we're trying to make here is that this starter is about auto-configuring the infrastructure when you want to use Wavefront. I think we need to better understand your use case (or better explain our objections) to move forward. To recap, we feel that the absence of `WavefrontSender` is a strong enough signal that the user does not want to emit data to Wavefront. With that in mind, we don't auto-configure the infrastructure. 

I understand you have a use case where you have a mixed case (not emitting metrics or spans to wavefront) but using the infrastructure to propage spans for logging purpose. Can we agree this use case is not Wavefront related? If we do, it feels wrong to me that we auto-configure it. 

That doesn't mean we can't improve what we have to make that use case easier though and I am open to suggestions to make that happen.

> For Sleuth side, since WavefrontTracingSleuthConfiguration only add WavefrontSleuthSpanHandler, the presence of WavefrontSender doesn't affect the creation of tracer, which is created somewhere else.

I don't know what you mean by that. `WavefrontTracer` is only auto-configured in`WavefrontTracingOpenTracingConfiguration` and this has a `@ConditionalOnMissingBean(name = WavefrontTracingSleuthConfiguration.BEAN_NAME)` so that it backs off as soon as Sleuth is configured.

**Comment by ttddyy** [comment]
> Can we agree this use case is not Wavefront related?

Hm, I think I'm half agree.
The part I agree is that we don't send data to Wavefront in on-prem setting. So it is not WF related. But, on the other half it's relevant to WF is that yet we want to use the `WavefrontTracer` implementation. Since WF tracer is the one we use for non on-prem settings, we don't want to bring in different tracer implementation as different code path for on-prem setup.

If WF-starter doesn't provide `WavefrontTracer` bean without `WavefrontSender`, we need to pretty much duplicate `wavefrontTracer` bean definition(`WavefrontTracingOpenTracingConfiguration`) which I wanted to avoid and hence the original motivation of this PR. 

Another way I could think of is to put the WF tracer bean definition to be an independent configuration class and separate from conditions(`@ConditionalOnBean(WavefrontSender.class)`).
So that, WF-starter imports the config with condition that requires `WavefrontSender`, but in our library we can have another condition to import this configuration.
Though, this requires the configuration class to be public, which may not be a normal pattern in spring-boot.

> > For Sleuth side, since WavefrontTracingSleuthConfiguration only add WavefrontSleuthSpanHandler, the presence of WavefrontSender doesn't affect the creation of tracer, which is created somewhere else.

> I don't know what you mean by that. WavefrontTracer is only auto-configured inWavefrontTracingOpenTracingConfiguration and this has a @ConditionalOnMissingBean(name = WavefrontTracingSleuthConfiguration.BEAN_NAME) so that it backs off as soon as Sleuth is configured.

I meant, even if `wavefrontTracingCustomizer`(`WavefrontTracingSleuthConfiguration#BEAN_NAME`) is skipped, since zipkin brave tracer bean could be defined outside of WF-starter, the brave tracer is able to perform log correlation without sending data to WF.

**Comment by snicoll** [comment]
Just to clarify the position. We're not denying your use case and I think that comment clarifies a bit more what I thought I've understood. What we're saying is that switching off exports and then expecting half of the infrastructure to be configured anyway doesn't sound sane for an auto-configuration. 

This leaves us with two options:

1. Configuring a `WavefrontSender` that doesn't emit to Wavefront. After all, that's what your on-prem configuration is all about
2. Extract the configuration aspect of the tracer so that a custom use case like yours can easily get that setup

I am leaning towards 1 at thixs point (in particular as it would replace `management.metrics.export.wavefront.enabled=false`).  I have no idea how practical/easy that would be so I'll have to research that a bit.

>  since zipkin brave tracer bean could be defined outside of WF-starter

Yeah well, this is outside of the scope of this project so I am not sure we could use that as an argument I am afraid.

**Comment by ttddyy** [comment]
@snicoll Ok thanks for clarifying.

I agree with approach 1. 

One approach I would imagine is to have a local-only `WavefrontSender` implementation such as  `LocalOnlyWavefrontClient`, most likely in `wavefront-sdk-java` level.
This local-only WF sender won't simply send data to WF server but other part should be same as what `WavefrontClient` does.

Then, in Spring Boot, a new property like `management.metrics.export.wavefront.local-only` may create a `LocalOnlyWavefrontClient` bean instead of `WavefrontClient` bean.

If it is done in `WavefrontSender` implementation level,  probably WF starter does not need any changes.

**Comment by snicoll** [comment]
OK. We're not going to introduce a property for this as I don't think this is warranted at this point but we can always reconsider based on votes. 

@sushantdewan123 is there something on the SDK we could use to easily create a `WavefrontSender` that doesn't emit to Wavefront?

**Comment by hanwavefront** [comment]
We can add a no-op sender in the SDK.  Created and linked an issue for that.

**Comment by snicoll** [comment]
There is now a no-op sender so I believe this PR should be closed.

**Comment by ttddyy** [comment]
Yes, this is no longer needed with the no-op sender in place.
Thanks for the discussions.

@hanwavefront Not urgent, but I need a release on `wavefront-sdk-java` to use the no-op sender.

**Pull request closed without merging**
