### PR TITLE
Add actuator endpoint for Wavefront dashboard

### PR DESCRIPTION
**Pull request by snicoll**
This PR exposes an endpoint at `/actuator/wavefront` that redirects
to the Wavefront dashboard according to the current configuration.

If an account has been managed, a one time link is requested at every
invocation. If the account has been configured by the user, the
endpoint redirects to the Wavefront cluster.

Here is a demo:

Apr-22-2020 15-05-10

### CODE REVIEW

**Comment by snicoll** [comment]
Note to self: should add extra tests in case we have a token that is either outdated or if retrieving the user account failed.

**Comment by snicoll** [comment]
The test has been added. 

@panghy can I get a review or some feedback on this one? This is changing the structure a bit so having that on `master` will help merging further changes.

**Comment by panghy** [comment]
Oh, I was waiting for you to assign to me as reviewer =p

**Comment by snicoll** [comment]
Oops, sorry I didn't know I had to assign it for review. Thanks for merging!

**Pull request merged**
